services:
  web-app:
    image: zupup/webapp:latest
    user: "node"
    environment:
      - DB_USER=
      - DB_PASSWORD=
      - DB_HOST=
      - DB_PORT=
      - DB_DATABASE=
      - DB_SSL_CERT=
      - SESSION_SECRET=
      - EMAIL_PASSWORD=
    ports: # use if it is necessary to expose the container to the host machine
      - "3000:3000"
    restart: always